apiVersion: v1
kind: Service
metadata:
  name: hardhome-backend-service
  labels:
    app: hardhome-backend-service
spec:
  ports:
  - port: 3010
    name: backendport
  clusterIP: None
  selector:
    app: hardhome-backend-app