apiVersion: v1
kind: Secret
metadata:
  name: hardhome-secret
type: Opaque
data:
  aws-secret-key: {{ .Values.common.awsSecretKey | b64enc }}
stringData:
  aws-access-key: {{ .Values.common.awsAccessKey }}   
   