apiVersion: v1
kind: Service
metadata:
  name: hardhome-api-service
spec:
  type: NodePort
  selector:
    app: hardhome-api-app
  ports:
    - name: http-api
      protocol: TCP
      port: 3020
      targetPort: 3020 
      nodePort: 30007 